import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AnimatedBackground from "@/app/components/AnimatedBackground";
import Nav from "@/app/components/Tabs/Nav";

const dirtylineFont = localFont({
    src: [
        {
            path: "../public/fonts/Dirtyline 36daysoftype 2022.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../public/fonts/Dirtyline 36daysoftype 2022.woff",
            weight: "400",
            style: "normal",
        },
        {
            path: "../public/fonts/Dirtyline 36daysoftype 2022.ttf",
            weight: "400",
            style: "normal",
        },
    ],
    variable: "--font-dirtyline",
    display: "swap",
});

const nohemiFont = localFont({
    src: [
        {
            path: "../public/fonts/Nohemi-Regular.woff2",
            weight: "400",
            style: "normal",
        },
    ],
    variable: "--font-nohemi",
    display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${dirtylineFont.variable} ${nohemiFont.variable} antialiased`}>
    {/* Background for all pages */}
    <AnimatedBackground/>

    {/* NAV */}
    <Nav/>

    <main>{children}</main>
    </body>
    </html>
  );
}
