import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AnimatedBackground from "@/app/components/AnimatedBackground";
import AnimatedLogo from "@/app/components/AnimatedLogo";
import Tabs from "@/app/components/Tabs";

const dirtylineFont = localFont({
    src: [
        {
            path: "../public/fonts/Dirtyline 36daysoftype 2022.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../public/fonts/Dirtyline 36daysoftype 2022.woff",
            weight: "400",
            style: "normal",
        },
        {
            path: "../public/fonts/Dirtyline 36daysoftype 2022.ttf",
            weight: "400",
            style: "normal",
        },
    ],
    variable: "--font-dirtyline",
    display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} ${dirtylineFont.variable} antialiased`}>
    {/* Background for all pages */}
    <AnimatedBackground/>

    {/* TABS */}
    <Tabs/>

    {/* LOGO */}
    <div
        className="flex items-center justify-center min-h-screen scale-100 sm:scale-50 md:scale-60 lg:scale-70 xl:scale-80">
        <AnimatedLogo/>
    </div>


    {/* Page content */}
    {children}
    </body>
    </html>
  );
}
